name: fintracker
description: A new Flutter project.
publish_to: 'none' # Prevent accidental publication to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.5.0 <4.0.0' # Proper SDK constraints

dependencies:
  flutter:
    sdk: flutter
  

  win32: ^5.3.0 # Correct placement
  flutter_localizations:
    sdk: flutter
  path: ^1.8.3 # Specified a compatible version
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  sqflite: ^2.2.8+2
  flutter_speed_dial: ^6.2.0
  events_emitter: ^0.5.2
  sqflite_common_ffi: ^2.2.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.1
  currency_picker: ^2.0.16
  material_symbols_icons: ^4.2741.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  file_picker: ^8.0.0+1
  http: ^1.2.2
  flutter_gemini: ^2.0.5
  google_generative_ai: ^0.4.6
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/currencies.json